// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gfxrxhqchbcgyiboovyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmeHJ4aHFjaGJjZ3lpYm9vdnl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNzExMzksImV4cCI6MjA2NTg0NzEzOX0.BBqg6FXsY_rpkXYSgHArGI6SVc-dM0bC_PNsURVI68Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);